# Site
repository: sproogen/jameswgrant
favicon: images/favicon.ico

version: 2

# Personal info
name: Swetamber Das
title: University of Massachusetts Boston
email: swetdas@gmail.com

# Social links
twitter_username: sproogen
github_username: SwetamberD
# dribbble_username:
# facebook_username:
# flickr_username:
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# pinterest_username:
# youtube_username:

# About Section
# about_title: About Me
about_profile_image: images/Das_Swet.jpg
about_content: | 
 about_content: | 
  I am a theoretical physicist by training and currently working as a research assistant professor in the Green research group at Mass Boston. My research interests lie at the intersection of dynamical systems and non-equilibrium physics.

  For my ongoing research with [Prof. Jason R. Green](https://www.jasonrgreen.net/), I am currently focused on developing a classical density theory that draws remarkable parallels with the density matrix formulation of quantum mechanics.

  One major breakthrough of this theory is that it provides a family of time-information uncertainty relations for deterministic systems, including those that are relevant to Lyapunov exponents and phase space dissipation rate. Another success is that the theory has led to a classical speed limit on thermodynamic entropy production.




content:
  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: NatWest
        sub_title: Lead Frontend Software Engineer
        caption: July 2021 - Present
        description: |
          Taken accountability for the frontend of the payments product area within a commercial banking platform, becoming a go to for knowledge and technical decisions.

          Currently developing a new frontend architecture transforming the current monolithic frontend application into a scalable modular application with micro-frontends
          using Webpack Module Federation. This has been a great experience to develop a new workflow for developers to develop and release code and have input in all aspects
          of the development workflow.

          I have also been a key part of our frontend interview provess, I have worked to improve our interview process including writing new code tests, whilst interviewing
          candidates across multiple countries.

      - layout: left
        border: weak
        title: NatWest
        sub_title: Frontend Software Engineer
        caption: August 2017 - July 2021
        description: |
          Working at NatWest as a front end engineer focusing mostly on a corporate banking product called Bankline.
          Working as part of a scrum team consiting of 5 developers, 2 testers and a PO/BA I have the oportunity to help drive the team forwards and
          work with the PO defining what we are building.

          I spend most of my time working on a specifc area of a large application that our team take ownership over. The front end is a <mark>React</mark> app
          that talks to an API built using a collection of <mark>Java</mark> microservices. I have spent time working in multiple parts of the stack including
          helping to define our front end architecure to follow best practices to implementing PDF and CSV export in a microservice.

          Last year I took the lead on rebuilding the login journey to our application. I worked with the architects and designers to create something that would
          be fit for purpose and be easy to maintain for years to come. I then built this to a high standard which lead to a seamless switch over from the previous
          system with no issues. More recently I have acted as a consultant to external teams and application architects to advise on how we should be building new
          functionality within our application. I have also built reusable components to the same standards as opensource libraries which have been used by different teams across the bank.

          I enjoy learning about all areas of our application which allows me to
